### ISSUE TITLE
Using Wombat Extensions

### ISSUE THREAD

**Issue by adavanisanti** [nebulab/cangaroo#5]
Hi - I am trying to figure out how to use Wombat integrations with Cangaroo. Could you provide some instructions or tutorials that can help me with this? I created a new rails app with postgresql DB, included cangaroo in Gemfile, ran migrations, and edited the routes. 

Thanks
Santi

**Comment by bricesanchez** [comment]
:+1:  I've deployed the Wombat Shopify integration on Heroku and now i don't know how to connect it to my Cangaroo app.

**Comment by iloveitaly** [comment]
@adavanisanti @bricesanchez Have you created a `Cangaroo::Connection` and configured jobs?

**Comment by bricesanchez** [comment]
@iloveitaly @AlessioRocco helped me to figure out how to use the shopify_integration with Cangaroo. 

Finally it's simple : 

1. Clone the shopify_integration and started it with the code into https://github.com/wombat/shopify_integration/blob/master/Procfile
`bundle exec unicorn -p 4000 -c ./config/unicorn.rb`

2. Create a product job inside your Cangaroo app :

```ruby
# app/jobs/cangaroo/product_job.rb
module Cangaroo
  class ProductJob < Cangaroo::Job
    connection 'Shopify'
    path '/add_product'

    def transform
      {
        product: {
          id: 'SKUPRODUCT',
          name: "Burton Custom Freestlye 153",
          description: 'Descrizione',
          meta_description: "<strong>Good snowboard!<\/strong>",
          options: [
            "Snowboard"
          ]
        }
      }
    end
  end
end
```

3. Add a `Cangaroo::Connection` like this in your rails console

```ruby
=> #<Cangaroo::Connection id: 1, name: "Shopify", url: "http://127.0.0.1:4000", key: "123", token: "123", created_at: "2016-03-15 21:22:38", updated_at: "2016-03-15 21:22:38", parameters: {:shopify_apikey=>”yourkey", :shopify_password=>”yourpassword", :shopify_host=>”yourhost”}>
```

4. Then run this in your rails console
```ruby
Cangaroo::ProductJob.perform_now
```

And :tada:  you have a new product in your Shopify app

**Comment by adavanisanti** [comment]
@bricesanchez Thanks for the steps. This helped me understand the data flow.

**Comment by AlessioRocco** [comment]
@adavanisanti finally I had time to written a blogpost on how to using extensions http://nebulab.it/blog/integrate-your-solidus-store-with-external-services-using-cangaroo/. 
I close this issue in favor of this post.

**Comment by bricesanchez** [comment]
@AlessioRocco nice! Could you do the same with the PollJob ?
