### ISSUE TITLE
Create User Interface

### ISSUE THREAD

**Issue by davidlaprade** [nebulab/cangaroo#57]
I'm in the process of making a user interface for cangaroo and would like to run some ideas by you guys.

I currently have this working on my end but haven't pushed anything to public projects yet. Here are a couple of screenshots:

![image](https://user-images.githubusercontent.com/7997618/35738958-387e106c-07fe-11e8-8306-9b6b1a83c2fb.png)

![image](https://user-images.githubusercontent.com/7997618/35738996-56de08aa-07fe-11e8-9982-7f38a1c1e917.png)

JSON payloads are editable. I'm in the process of adding retry/resolve functionality to it too, similar to what Wombat had.

### Design Goals
* __optional__
   * users have to opt-into the interface as an add-on to cangaroo -- by default, cangaroo doesn't change
   * backwards-compatible for existing users to upgrade to the newest version
   * users can decide on a per-job basis whether they want that job tracked in the GUI
* __general__
  * support PushJobs and PollJobs
  * any payload type
  * any DB type
  * any worker (delayed_job, redis, etc)
* __minimal__
  * no invasive monkey-patching
  * no modifications to the cangaroo core
  * only two new DB tables and some ActiveJob callbacks
* __simple__
  * track jobs through the GUI with a single `include` in the job class
  * no authentication (leaves people free to use Devise, HTTP Basic, or whatever else they want)
  * no fancy JS to pre-compile or anything
  * bootstrap styles

My company is interested in open-sourcing this code. I figure there are two ways we could do that. Either:
1. by incorporating it into the cangaroo core project, or
2. by making a separate gem, e.g. `cangaroo-interface`

What would be your preference?

**Comment by bricesanchez** [comment]
Hi @davidlaprade, it looks awesome! 

I think the best way should be to make a separate gem. It's the best way to get things done!

I can't wait to see the result :)

**Comment by davidlaprade** [comment]
Awesome. Thanks for the encouragement, @bricesanchez!

I'm in the process of pulling out the code into a separate repo now.

One thing that would be a big help to me is if you guys would bump the cangaroo version and upload the most recent code to [rubygems](https://rubygems.org/gems/cangaroo). The version that's up there is a bit old (May 2016), and as a result, I can't get my tests passing with a normal `gemspec` file -- as my tests presuppose the new code on master. But I'd really love to have cangaroo in there as an official dependency of the UI. :)

**Comment by bricesanchez** [comment]
@davidlaprade, i don't have the rights to release a new gem but in waiting for this you could add the github url of cangaroo gem in your Gemfile:

```
# Gemfile
gem 'cangaroo', git: 'https://github.com/nebulab/cangaroo', branch: 'master'
```

It will allow CI to use the current master branch instead of the released gem when running the specs

**Comment by davidlaprade** [comment]
Got it. Thanks @bricesanchez.

I'd totally just source the gem from github. I think that's a good solution. But unfortunately my issue isn't with the Gemfile, but with the gem's gemspec. I want to include cangaroo as a dependency of the interface gem, so that anyone who includes the interface gem in his/her Gemfile will also get cangaroo along with it. But:
* the version of cangaroo in rubygems is out of date, and won't work with the UI, and
* [you can't specify a github source for a gem in a gemspec](https://stackoverflow.com/a/6499472/3680688) like you can in a Gemfile

This isn't a huge deal. For now I'll just put a note in the README that anyone using the UI needs to manually add the github cangaroo to his/her Gemfile. But going forward, I'd love to have this be automatic!

**Comment by bricesanchez** [comment]
You should do this: 

```
# cangaroo_interface.gemspec
s.add_dependency    'cangaroo',              ['>=1.2.0', '~>1.2']
```

and 

```
# Gemfile of your Cangaroo Interface
gem 'cangaroo', git: 'https://github.com/nebulab/cangaroo', branch: 'master'
```

Then you will have to "put a note in the README that anyone using the UI needs to manually add the github cangaroo to his/her rails app Gemfile".

Finally, @AlessioRocco or @kennyadsl, could you release a new version of Cangaroo?

**Comment by bricesanchez** [comment]
@davidlaprade There is a new version of Cangaroo: https://rubygems.org/gems/cangaroo

**Comment by davidlaprade** [comment]
Perfect, thanks @bricesanchez!

**Comment by davidlaprade** [comment]
Update from my end: the interface has been running in production for a couple weeks right now. I just have a couple more things to clean up on my end before I make the repo public. We're very close!

**Comment by davidlaprade** [comment]
Alright, the gem is now public: https://github.com/ascensionpress/cangaroo_ui

Thanks for the support everyone!
